### ISSUE TITLE
syntax config.cson

### ISSUE THREAD

**Issue by opeeters** [execjosh/atom-file-types#31]
the syntax for in `~/.atom/config.cson` seems to have changed slightly (is this maybe new in atom 1.0?). taking the example given for `.ex_em_el` files should be:
```
  "file-types":
    ex_em_el: "text.xml"
```
Thanks for the package! Very usefull when working with lots of custom file extentions!

**Comment by execjosh** [comment]
I don't see what you mean.  It still works for me...?

**Comment by opeeters** [comment]
well, in your readme.md you have it as:
```
'file-types':
  'ex_em_el': 'text.xml'
```
(single quotes for all elements instead of double qoutes only for the names)
This did not work for me..

**Comment by execjosh** [comment]
Hmm...  Single- and double-quotes work for my OS X Atom v1.0.2...

**Comment by yordis** [comment]
@execjosh I put single-quotes I reload and my file change to double-quotes.

And this is not working for me because I put it with single/doble quotes and then goes away when I reload so something is no right now.

Atom: 1.0.5

**Comment by execjosh** [comment]
Atom uses the [season](https://github.com/atom/season) package to read/write CSON.

**Comment by yordis** [comment]
@execjosh sorry man, what does that come from? I mean the reason why you say just only that

**Comment by michaelrommel** [comment]
Same problem here. It removes the quotes from the extension and  puts double quotes around the scope. But I cannot even add a second extension, they are just thrown away... No explanation, how this is supposed to work, comma or not, braces or not...

**Comment by yordis** [comment]
@michaelrommel thanks a lot

**Comment by execjosh** [comment]
Hey guys.  I'm really sorry you're having problems with this extension.

@yordis 

> @execjosh sorry man, what does that come from? I mean the reason why you say just only that

My response was very terse, I apologize.  I meant to say that anything `season` thinks is valid is what is valid.  I guess I have misinterpreted your problem...


@michaelrommel 

> Just found out, that this package is no longer needed. config.cson now supports extending right off the bat under "core":

Woah, cool.

**Comment by tonedef** [comment]
I wouldn't say this package is 'no longer needed'. customFileTypes in atom itself shows that it's clearly desired, but they didn't include regex for it (not that I saw anyway), and that for me is the whole reason I use the file-types package. Totally appreciate the effort @execjosh  put into it, without it, I would not be using atom at work right now due to our really odd file naming scheme. It's easy to use once you know how:

1. Under the *atom* menu, click on *Open Your Config*, this will open up your config.cson file
2. Add   **"file-types":** under the main section
3. Under that, add the file type you want, e.g. **"^css":"source.css"**

Be careful of indentation. It matters.

Here's an example config.cson file:

     "*":
      "exception-reporting":
        userId: "xxx-yyy-zzz-1111-2222222"
      welcome:
        showOnStartup: false
      editor:
        invisibles: {}
        softWrap: true
        showIndentGuide: true
        showInvisibles: true
        tabLength: 4
      "file-types":
        "^javascript": "source.js"
        "^css": "source.css"
        "^(vice_page_|header)": "text.html.basic"
        ".*less-": "source.css.less"


ftr, this is totally 100% working on atom v1.0.19

**Comment by execjosh** [comment]
@tonedef  Thank you for your kind words and verification!

I also use mainly the regexp matching personally...

**Comment by execjosh** [comment]
I am calling this resolved...
